### ISSUE TITLE
[bug] "volumes

### ISSUE THREAD

**Issue by TechQuery** [composerize/decomposerize#39]
**Do you want to request a *feature* or report a *bug*?**

- [ ] feature request
- [ ] bug report

**Please provide a sample input docker run command**
```yaml
nginx:
    ports:
        - '80:80'
    volumes:
        - '/var/run/docker.sock:/tmp/docker.sock:ro'
    image: nginx
```

**What is the current output?***
```
some output
```

**What is the expected/desired output?**
```
some better output
```

Thanks for following this template and making decomposerize better for everyone else too!
