### ISSUE TITLE
[bug] "volumes" field support is missing

### ISSUE THREAD

**Issue by TechQuery** [composerize/decomposerize#40]
@composerize I'm using the online version: https://ray.run/tools/docker-compose-to-docker-run

## Do you want to request a *feature* or report a *bug*?

- [ ] feature request
- [x] bug report

## Please provide a sample input docker run command

If I input a simplified configuration, `decomposerize` returns `docker run` commands without `docker volume` command, which will failed to start containers without the needed volume:

```yaml
version: "3"

volumes:
  polyfill-cache:
    driver: juicedata/juicefs
    driver_opts:
      name: polyfill-cache
      metaurl: postgres://postgres:${META_PASSWORD}@meta-server:5432/juicefs
      storage: ${STORAGE_TYPE}
      bucket: ${BUCKET}
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

services:
  meta-server:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=juicefs
      - POSTGRES_PASSWORD=${META_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data/
    restart: always

  api-service:
    depends_on:
      - meta-server
    image: polyfiller/api-service
    environment:
      - NODE_ENV=production
    volumes:
      - polyfill-cache:/tmp/@wessberg/polyfiller
    restart: always
```

then input the whole original configuration, an error thrown:

```yaml
version: "3"

volumes:
  polyfill-cache:
    driver: juicedata/juicefs
    driver_opts:
      name: polyfill-cache
      metaurl: postgres://postgres:${META_PASSWORD}@meta-server:5432/juicefs
      storage: ${STORAGE_TYPE}
      bucket: ${BUCKET}
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

networks:
  polyfiller:

services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  meta-server:
    depends_on:
      - autoheal
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=juicefs
      - POSTGRES_PASSWORD=${META_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data/
    networks:
      - polyfiller
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
    labels:
      - autoheal=true
    restart: always

  api-service:
    depends_on:
      - autoheal
      - meta-server
    image: polyfiller/api-service
    environment:
      - NODE_ENV=production
    volumes:
      - polyfill-cache:/tmp/@wessberg/polyfiller
    networks:
      - polyfiller
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 300000000s
      retries: 5
      start_period: 30s
    labels:
      - autoheal=true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m

  caddy:
    depends_on:
      - api-service
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - polyfiller
    restart: always
    command: caddy reverse-proxy --from polyfiller.app --to api-service:3000
```

## What is the current output?

```shell
docker run -e POSTGRES_USER=postgres -e POSTGRES_DB=juicefs -e POSTGRES_PASSWORD=${META_PASSWORD} -v ./data:/var/lib/postgresql/data/ --restart always postgres
docker run -e NODE_ENV=production -v polyfill-cache:/tmp/@wessberg/polyfiller --restart always polyfiller/api-service
```
or

```text
A.forEach is not a function
```

## What is the expected/desired output?

```shell
docker volume create --driver juicedata/juicefs \
  --opt name=polyfill-cache
  --opt metaurl=postgres://postgres:${META_PASSWORD}@meta-server:5432/juicefs
  --opt storage=${STORAGE_TYPE}
  --opt bucket=${BUCKET}
  --opt access-key=${ACCESS_KEY}
  --opt secret-key=${SECRET_KEY}
  polyfill-cache
docker run  -v ./data:/var/lib/postgresql/data/ \
  -e POSTGRES_USER=postgres
  -e POSTGRES_DB=juicefs
  -e POSTGRES_PASSWORD=${META_PASSWORD}
  --restart always
  postgres
docker run  -v polyfill-cache:/tmp/@wessberg/polyfiller \
  -e NODE_ENV=production
  --restart always
  polyfiller/api-service
```
