### ISSUE TITLE
Mappings are not supported for service environment, labels, and sysctls

### ISSUE THREAD

**Issue by mrnoname1000** [composerize/decomposerize#73]
**Do you want to request a *feature* or report a *bug*?**

- [ ] feature request
- [x] bug report

Pretty self-explanatory, as per [the Compose Specification](https://docs.docker.com/compose/compose-file/05-services/) some elements can be either an array or a mapping, the latter of which is not recognized by decomposerize.

**Please provide a sample input docker run command**
```yaml
services:
  alpine:
    image: alpine
    environment:
      NODE_ENV: production
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    sysctls:
      net.core.somaxconn: 1024
      net.ipv4.tcp_syncookies: 0
```

**What is the current output?***
```
docker run -e "[object Object]" -l "[object Object]" --sysctl "[object Object]" alpine
```

**What is the expected/desired output?**
```
docker run -e NODE_ENV=production -l com.centurylinklabs.watchtower.enable=false --sysctl net.core.somaxconn=1024 --sysctl net.ipv4.tcp_syncookies=0 alpine
```

**Comment by sharevb** [comment]
Hi @mrnoname1000, thanks for this bug report, it should be ok now on the website (and npm package)

**Comment by Oaklight** [comment]
environment variables still missing from the decomposerize results, just tested on the website:
![图片](https://github.com/user-attachments/assets/d800aa9a-030d-44ef-bb29-0059947a5639)

**Comment by sharevb** [comment]
Hi @Oaklight, if I refer to https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/, this compose is not valid (so -e options not emitted). I don't know (and tested) if `docker-compose` will either ignore or raise a warning or error.

It should be either be: 
```
services:
  paradedb:
    image: oaklight/vectorsearch
    container_name: vectorsearch
    environment:
      - POSTGRES USER=myuser
      - POSTGRES_PASSHORD=mypassword
      - POSTGRES_DB=nydatabase
    ports:
      - 5432:5432
    volumes:
      - $pwd/pgdata: /var/lib/postgresql/data/
```

or

```
services:
  paradedb:
    image: oaklight/vectorsearch
    container_name: vectorsearch
    environment:
      POSTGRES USER: myuser
      POSTGRES_PASSHORD: mypassword
      POSTGRES_DB: nydatabase
    ports:
      - 5432:5432
    volumes:
      - $pwd/pgdata: /var/lib/postgresql/data/
```

**Comment by Oaklight** [comment]
Thanks for the notice. I'm using a GUI interface to manage docker, and the compose file in the snapshot was indeed auto-corrected to the second version in your reply. 

Maybe consider adding a notice of syntax error in the future release?

**Comment by sharevb** [comment]
Hi @Oaklight, I finally decided to handle this "autorepair" case

**Comment by Oaklight** [comment]
@sharevb I just tested the vectorsearch buggy compose on the decomposerize.com
```
services:
  paradedb:
    image: oaklight/vectorsearch
    container_name: vectorsearch
    environment:
      - POSTGRES USER: myuser
      - POSTGRES_PASSHORD: mypassword
      - POSTGRES_DB: nydatabase
    ports:
      - 5432:5432
    volumes:
      - $pwd/pgdata:/var/lib/postgresql/data/
```
this was corrected.

but this got trapped:
```
services:
  paradedb:
    image: oaklight/vectorsearch
    container_name: vectorsearch
    environment:
      - POSTGRES USER:myuser
      - POSTGRES_PASSHORD:mypassword
      - POSTGRES_DB:nydatabase
    ports:
      - 5432:5432
    volumes:
      - $pwd/pgdata:/var/lib/postgresql/data/
```
as
```
docker run --name vectorsearch -e "POSTGRES USER:myuser" -e POSTGRES_PASSHORD:mypassword -e POSTGRES_DB:nydatabase -p 5432:5432 -v $pwd/pgdata:/var/lib/postgresql/data/ oaklight/vectorsearch
```
